apiVersion: v2
name: common
description: A Helm chart for Kubernetes
icon: https://i0.wp.com/divistant.com/wp-content/uploads/2020/10/color_favicon.png
type: application
version: 0.1.0
appVersion: "0.1.0"